apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-backend-secret
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  django_secret_key: {{ .Values.backend.secretKey | quote }}